### ISSUE TITLE
Revert the script

### ISSUE THREAD

**Issue by Emilien-Etadam** [simeononsecurity/Windows-Optimize-Debloat#3]
Is there any way to put back everything as before ? 
Too many things are not working normaly since  I run the script.

**Comment by simeononsecurity** [comment]
The script implements a restore point. Try using that. Otherwise, you'll be left with reinstalling windows from scratch.
This script also doesn't do any hardening or the like, it's just privacy changes and optimizations. So it shouldn't break really anything. Could you please provide some more details about the issues you're having?

**Comment by Emilien-Etadam** [comment]
This kind of thing that didn't happen before : 
![Yn3xgg3h7I](https://user-images.githubusercontent.com/56485277/221930288-d5f61786-a9e1-4009-b354-9c916022edc8.jpg)

**Comment by Emilien-Etadam** [comment]
Also this thing when I shutdown the PC: 

![4LzJUfiXlN](https://user-images.githubusercontent.com/56485277/221931140-13589715-18b5-4783-89d9-7604e4f5c750.jpg)

Not only with this program.

**Comment by simeononsecurity** [comment]
The COM Surrogate is a part of windows. It is responsible for many things. 
However to me it seems that a virus scan or file scan is going on in the background. 
Safely reboot and then let the system run its course. Those issues will resolve themselves.
